### ISSUE TITLE
[Oparin] IBM PowerVC Enhancements

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/manageiq-providers-ibm_power_vc#46]
- [x] Metrics collection (able to inherit functionality from openstack)
- [x] Image Import PVS->PVC https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/38

---

- [x] VM console access https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/69
- [ ] Template provisioning from instance
- [x] Instance snapshots (able to inherit functionality from openstack)
- [ ] Events

---

- Najdorf: https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/issues/27

**Comment by Fryguy** [comment]
@agrare Moving forward, we are going to stop using umbrella issues, and there should be separate issues for each major enhancement that should be put on the roadmap directly.  As such I'm closing this one.

**Comment by jaywcarman** [comment]
@Fryguy @agrare I created a new issue to track PowerVC events targeted for Petrosian: #75 

Is there anything I need to add besides the Label: `enhancement` and Milestone: `Petrosian`? I don't think I have auth to add an issue to the Roadmap project.
