### ISSUE TITLE
Create data migration to fix up PowerVC record types

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-ibm_power_vc#60]
Fix the `:type` column of existing records that have the incorrect STI class names.

https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/52
https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/53
https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/55

**Comment by jaywcarman** [comment]
All of the fix PRs have been merged.
