### ISSUE TITLE
Add/verify support for Ceilometer events

### ISSUE THREAD

**Issue by jaywcarman** [ManageIQ/manageiq-providers-ibm_power_vc#75]
PowerVC supports the following [OpenStack Event (Panko) APIs][1]:
- GET /v2/events
- GET /v2/events/{message_id}

Panko provides event data from [Ceilometer][2]:
> The Panko project is an event storage service that provides the ability to store and querying event data generated by Ceilometer with potentially other sources.

Support for Ceilometer events is already present in the MIQ OpenStack provider - perhaps it the existing functionality can be inherited by PowerVC. 

[1]: https://www.ibm.com/docs/en/powervc/2.1.0?topic=apis-supported-openstack-event-panko
[2]: https://docs.openstack.org/panko/latest/

**Comment by iv1111** [comment]
@Guddetisandeep will take this issue.

**Comment by iv1111** [comment]
@Fryguy could you add @Guddetisandeep to the project as a member?

**Comment by Guddetisandeep** [comment]
Panko gets event data from the Ceilometer service in OpenStack. Ceilometer collects event data from various OpenStack services, including compute, storage, and networking, and stores the data in a database. Panko provides an API for querying and retrieving this event data and PowerVC supports the following [Openstack Event Panko APIs](https://www.ibm.com/docs/en/powervc/2.1.0?topic=apis-supported-openstack-event-panko)

When an event occurs in OpenStack, it is sent to the Ceilometer service, which records the event data in the database. Panko can then be used to retrieve the event data using a REST API, and this data can be consumed by external systems, such as billing and monitoring tools. Panko provides a simple and convenient way to access the event data collected by Ceilometer.

Here is the Implementation of OpenStack Ceilometer Event Monitor functionality in ManageIQ  Provider OpenStack:
[OpenStack Ceilometer event monitor](https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb)

This Document gives the Information about 
[IBM PowerVC Event Management](https://community.ibm.com/community/user/power/blogs/abhishek-sharma-m1/2018/07/13/ibm-powervc-event-management)

**Comment by iv1111** [comment]
Thanks. I guess the next step would be to try the functionality on a PowerVC instance and verify whether the metrics get generated and shown on the MIQ UI properly.

**Comment by jaywcarman** [comment]
Fixed by #89
